{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "dingodocs.fullname" . }}-runtime
  labels:
    {{- include "dingodocs.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ include "dingodocs.secretName" . }}
    creationPolicy: Owner
  {{- with .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- range . }}
    - extract:
        key: {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- with .Values.externalSecret.data }}
  data:
    {{- range . }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteKey | quote }}
        {{- with .property }}
        property: {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
